# -*- coding: utf-8 -*-
"""q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RUJ-gyyU6TTFmLPLKFD79WmSyBtllw0
"""

OK_FORMAT = False
name = "q1"
from nose.tools import assert_equal  # Import necessary testing tools

# Test function for question 1
def test_even_odd_numbers():
    # Call your function with an input
    result = even_odd_numbers(10)

    # Assert that the output matches the expected value
    assert_equal(result, ([2, 4, 6, 8, 10], [1, 3, 5, 7, 9]))