# -*- coding: utf-8 -*-
"""q11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RUJ-gyyU6TTFmLPLKFD79WmSyBtllw0
"""

OK_FORMAT = False
name = "q11"



import pandas as pd

def calculate_price_stats(df):
    """
    Calculates the mean, median, and mode of the `price` and `usdprice` columns for each `category`.

    Args:
        df (pd.DataFrame): The input dataframe.

    Returns:
        tuple: A tuple of two dataframes: (price_stats, usdprice_stats).
    """
    df = df.copy()  # Avoid modifying the original dataframe

    # Group by category and calculate mean & median
    price_stats = df.groupby("category")["price"].agg(["mean", "median"]).reset_index()
    usdprice_stats = df.groupby("category")["usdprice"].agg(["mean", "median"]).reset_index()

    # Calculate mode separately (mode can return multiple values, so take the first one)
    price_mode = df.groupby("category")["price"].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None).reset_index()
    usdprice_mode = df.groupby("category")["usdprice"].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None).reset_index()

    # Merge mode values into the existing stats
    price_stats = price_stats.merge(price_mode, on="category").rename(columns={"price": "mode"})
    usdprice_stats = usdprice_stats.merge(usdprice_mode, on="category").rename(columns={"usdprice": "mode"})

    return price_stats, usdprice_stats