# -*- coding: utf-8 -*-
"""q12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RUJ-gyyU6TTFmLPLKFD79WmSyBtllw0
"""

OK_FORMAT = False
name = "q12"


def merge_dataframes(cereals_df, pulses_df):
    """
    Merges the two dataframes back into one dataframe and saves it as `merged_data.csv`.

    Args:
        cereals_df (pd.DataFrame): The cereals and tubers dataframe.
        pulses_df (pd.DataFrame): The pulses and nuts dataframe.

    Returns:
        pd.DataFrame: The merged dataframe.
    """
    # Concatenate the two dataframes
    merged_df = pd.concat([cereals_df, pulses_df], ignore_index=True)

    # Save to CSV
    merged_df.to_csv("merged_data.csv", index=False)

    return merged_df