# -*- coding: utf-8 -*-
"""q13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RUJ-gyyU6TTFmLPLKFD79WmSyBtllw0
"""

OK_FORMAT = False
name = "q13"

def select_columns():
    """
    Opens the `merged_data.csv` file and selects only the `date_new`, `market`, `commodity`, `price`, and `usdprice` columns.

    Returns:
        pd.DataFrame: The dataframe with selected columns.
    """
    # Load the dataset
    df = pd.read_csv("merged_data.csv")

    # Select the required columns
    selected_columns = ["date_new", "market", "commodity", "price", "usdprice"]
    df_selected = df[selected_columns]

    return df_selected