# -*- coding: utf-8 -*-
"""q14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RUJ-gyyU6TTFmLPLKFD79WmSyBtllw0
"""

OK_FORMAT = False
name = "q14"

def calculate_state_avg_prices(df):
    """
    Groups the data by `admin1` (state) and calculates the average `price` and `usdprice` for each state.

    Args:
        df (pd.DataFrame): The input dataframe.

    Returns:
        pd.DataFrame: The dataframe with average prices by state.
    """
    # Group by admin1 (state) and calculate mean price and usdprice
    state_avg_prices = df.groupby("admin1")[["price", "usdprice"]].mean().reset_index()

    return state_avg_prices