# -*- coding: utf-8 -*-
"""q15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RUJ-gyyU6TTFmLPLKFD79WmSyBtllw0
"""

OK_FORMAT = False
name = "q15"

def identify_top_markets(df):
    """
    Identifies the top 5 markets with the highest average `usdprice` for `Rice (imported)`.

    Args:
        df (pd.DataFrame): The input dataframe.

    Returns:
        pd.Series: A series with the top 5 markets and their average `usdprice`.
    """
    # Filter data for "Rice (imported)"
    rice_df = df[df["commodity"] == "Rice (imported)"]

    # Group by market and calculate the average usdprice
    top_markets = rice_df.groupby("market")["usdprice"].mean().nlargest(5)

    return top_markets