# -*- coding: utf-8 -*-
"""q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RUJ-gyyU6TTFmLPLKFD79WmSyBtllw0
"""

OK_FORMAT = False
name = "q2"

def word_frequency(paragraph):
    """
    Returns a dictionary of word frequencies in a paragraph.

    Args:
        paragraph (str): The input paragraph.

    Returns:
        dict: A dictionary with words as keys and their frequencies as values.
    """
    words = paragraph.split()  # Split the paragraph into individual words
    word_counts = {}  # Initialize an empty dictionary to store word frequencies

    for word in words:
        word = word.strip('.,!?"').capitalize()  # Remove punctuation and capitalize
        if word:  # Check if the word is not empty after removing punctuation
            word_counts[word] = word_counts.get(word, 0) + 1

    return word_counts  # Return the dictionary of word frequencies