# -*- coding: utf-8 -*-
"""q3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RUJ-gyyU6TTFmLPLKFD79WmSyBtllw0
"""

OK_FORMAT = False
name = "q3"

def extract_and_sort_values(dictionary):
    """
    Extracts and sorts dictionary values in descending order.

    Args:
        dictionary (dict): The input dictionary.

    Returns:
        list: A list of sorted values in descending order.
    """
    values = list(dictionary.values())  # Extract values into a list
    values.sort(reverse=True)  # Sort in descending order
    return values  # Return the sorted list