# -*- coding: utf-8 -*-
"""q4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RUJ-gyyU6TTFmLPLKFD79WmSyBtllw0
"""

OK_FORMAT = False
name = "q4"

def merge_lists_to_dict(keys, values):
    """
    Merges two lists into a dictionary.

    Args:
        keys (list): List of keys.
        values (list): List of values.

    Returns:
        dict: A dictionary with keys and values paired.
    """
    merged_dict = dict(zip(keys, values))  # Merge using zip and dict
    return merged_dict  # Return the merged dictionary