# -*- coding: utf-8 -*-
"""q6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RUJ-gyyU6TTFmLPLKFD79WmSyBtllw0
"""

OK_FORMAT = False
name = "q6"

def get_nearest_farthest(pt, points):
    """
    Returns the indices of the nearest and farthest points from a point of interest.

    Args:
        pt (tuple): The point of interest (x, y).
        points (list): List of points [(x1, y1), (x2, y2), ...].

    Returns:
        tuple: Indices of the nearest and farthest points.
    """
    distances = [(i, (x - pt[0])**2 + (y - pt[1])**2) for i, (x, y) in enumerate(points)]

    nearest_index = min(distances, key=lambda d: d[1])[0]
    farthest_index = max(distances, key=lambda d: d[1])[0]

    return nearest_index, farthest_index