# -*- coding: utf-8 -*-
"""q7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RUJ-gyyU6TTFmLPLKFD79WmSyBtllw0
"""

OK_FORMAT = False
name = "q7"


def filter_divisible(N, q):
    """
    Returns a list of numbers between 0 and N that are not divisible by q.

    Args:
        N (int): The upper limit.
        q (int): The divisor.

    Returns:
        list: A list of non-divisible numbers.
    """
    if N < 0:
        N = 20  # Use N = 20 if N is negative

    return [i for i in range(N) if i % q != 0]