# -*- coding: utf-8 -*-
"""q8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RUJ-gyyU6TTFmLPLKFD79WmSyBtllw0
"""

OK_FORMAT = False
name = "q8"


def flatten_and_unique(list_of_lists):
    """
    Flattens a list of lists and returns a sorted list of unique elements.

    Args:
        list_of_lists (list): A list of lists.

    Returns:
        list: A sorted list of unique elements.
    """
    unique_elements = set()  # Use a set to store unique elements

    for sublist in list_of_lists:
        unique_elements.update(sublist)  # Add elements from each sublist

    return sorted(unique_elements)  # Return a sorted list of unique elements