# -*- coding: utf-8 -*-
"""q9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RUJ-gyyU6TTFmLPLKFD79WmSyBtllw0
"""

OK_FORMAT = False
name = "q9"


def create_date_new(df):
    """
    Creates a new column `date_new` from the `date` column, converting it to a datetime format.

    Args:
        df (pd.DataFrame): The input dataframe.

    Returns:
        pd.DataFrame: The dataframe with the new `date_new` column.
    """
    df = df.copy()  # Avoid modifying the original dataframe
    df["date_new"] = pd.to_datetime(df["date"], errors="coerce")  # Convert to datetime
    return df